"""initial schema with all tables

Revision ID: f34dff938c10
Revises: 
Create Date: 2026-06-13 18:00:11.669025

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 — required for Geography/Geometry column types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f34dff938c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=False),
    sa.Column('shift_end', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('baseline_redelivery_rate', sa.Float(), nullable=True),
    sa.Column('takumi_redelivery_rate', sa.Float(), nullable=True),
    sa.Column('baseline_driver_seconds', sa.Float(), nullable=True),
    sa.Column('takumi_driver_seconds', sa.Float(), nullable=True),
    sa.Column('co2_baseline_g', sa.Float(), nullable=True),
    sa.Column('co2_takumi_g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address_type', sa.Enum('APARTMENT', 'HOUSE', name='address_type', native_enum=False), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'ADMIN', name='user_role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('availability_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('slot_code', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('attempt_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('was_home', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_availability_stop_slot', 'availability_history', ['stop_id', 'slot_code'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('parcel_size', sa.Enum('S60', 'S80', 'S100', 'S120', name='parcel_size', native_enum=False), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'DELIVERED', 'REDELIVERY', name='order_status', native_enum=False), nullable=False),
    sa.Column('assigned_slot_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_slot_code'], ['slots.code'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('max_route_seconds', sa.Integer(), nullable=False),
    sa.Column('cost_per_second', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='agent_direction', native_enum=False), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('parsed_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_taken', sa.Enum('PROPOSE_WINDOW', 'CONFIRM_DELIVERY', 'REQUEST_REPLAN', 'NO_ACTION', name='agent_action', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('policy', sa.Enum('BASELINE', 'TAKUMI', name='route_policy', native_enum=False), nullable=False),
    sa.Column('total_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', name='route_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('planned_arrival_min', sa.Integer(), nullable=True),
    sa.Column('assigned_slot_code', sa.String(length=10), nullable=True),
    sa.Column('predicted_home_prob', sa.Float(), nullable=True),
    sa.Column('actual_outcome', sa.Enum('SUCCESS', 'MISS', name='stop_outcome', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_stops')
    op.drop_table('routes')
    op.drop_table('agent_interactions')
    op.drop_table('vehicles')
    op.drop_table('orders')
    op.drop_index('ix_availability_stop_slot', table_name='availability_history')
    op.drop_table('availability_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('slots')
    op.drop_table('simulation_runs')
    op.drop_table('depots')
    # ### end Alembic commands ###
